package os.kei.ui.page.main.host.main

import androidx.compose.runtime.Stable
import os.kei.core.prefs.NonHomeBackgroundAlignment
import os.kei.core.prefs.NonHomeBackgroundContentScale
import os.kei.core.prefs.NonHomeBackgroundPageStyle
import os.kei.core.privilege.PrivilegedShell
import os.kei.mcp.server.McpServerManager
import os.kei.core.privilege.PrivilegeStatus

@Stable
internal data class MainScreenPagerCoordinator(
    val settingsReturnToken: Int,
    val liquidActionBarLayeredStyleEnabled: Boolean,
    val gripAwareFloatingDockEnabled: Boolean,
    val homeIconHdrEnabled: Boolean,
    val homeDynamicFullEffectEnabled: Boolean,
    val preloadingEnabled: Boolean,
    val nonHomeBackgroundEnabled: Boolean,
    val nonHomeBackgroundUri: String,
    val nonHomeBackgroundOpacity: Float,
    val nonHomeBackgroundContentScale: NonHomeBackgroundContentScale,
    val nonHomeBackgroundAlignment: NonHomeBackgroundAlignment,
    val nonHomeBackgroundPageStyle: NonHomeBackgroundPageStyle,
    val nonHomeBackgroundScrim: Float,
    val nonHomeBackgroundDepthEnabled: Boolean,
    val nonHomeBackgroundSaturation: Float,
    val visibleBottomPageNames: Set<String>,
    val onVisibleBottomPageNamesChange: (Set<String>) -> Unit,
    val privilegeStatus: PrivilegeStatus,
    val privilegedShell: PrivilegedShell,
    val mcpServerManager: McpServerManager,
    val onOpenGuideDetail: (String) -> Unit,
    val requestedBottomPage: String?,
    val requestedBottomPageToken: Int,
    val requestedGitHubRefreshToken: Int,
    val requestedGitHubActionsTrackId: String?,
    val requestedGitHubActionsSheetToken: Int,
    val requestedBaAccountId: String?,
    val requestedBaAccountToken: Int,
    val onRequestedBottomPageConsumed: () -> Unit,
    val onBaGuideCatalogOpen: () -> Unit,
    val onBaGuideCatalogBack: () -> Unit,
    val onOpenBaActivityCalendar: (Int?) -> Unit,
    val onOpenBaPool: (Int?) -> Unit,
)

internal fun buildMainScreenPagerCoordinator(
    settingsReturnToken: Int,
    prefsState: MainScreenUiPrefsState,
    privilegeStatus: PrivilegeStatus,
    privilegedShell: PrivilegedShell,
    mcpServerManager: McpServerManager,
    onOpenGuideDetail: (String) -> Unit,
    requestedBottomPage: String?,
    requestedBottomPageToken: Int,
    requestedGitHubRefreshToken: Int,
    requestedGitHubActionsTrackId: String?,
    requestedGitHubActionsSheetToken: Int,
    requestedBaAccountId: String?,
    requestedBaAccountToken: Int,
    onRequestedBottomPageConsumed: () -> Unit,
    onBaGuideCatalogOpen: () -> Unit,
    onBaGuideCatalogBack: () -> Unit,
    onOpenBaActivityCalendar: (Int?) -> Unit,
    onOpenBaPool: (Int?) -> Unit,
): MainScreenPagerCoordinator =
    MainScreenPagerCoordinator(
        settingsReturnToken = settingsReturnToken,
        liquidActionBarLayeredStyleEnabled = prefsState.liquidActionBarLayeredStyleEnabled,
        gripAwareFloatingDockEnabled = prefsState.gripAwareFloatingDockEnabled,
        homeIconHdrEnabled = prefsState.homeIconHdrEnabled,
        homeDynamicFullEffectEnabled = prefsState.homeDynamicFullEffectEnabled,
        preloadingEnabled = prefsState.preloadingEnabled,
        nonHomeBackgroundEnabled = prefsState.nonHomeBackgroundEnabled,
        nonHomeBackgroundUri = prefsState.nonHomeBackgroundUri,
        nonHomeBackgroundOpacity = prefsState.nonHomeBackgroundOpacity,
        nonHomeBackgroundContentScale = prefsState.nonHomeBackgroundContentScale,
        nonHomeBackgroundAlignment = prefsState.nonHomeBackgroundAlignment,
        nonHomeBackgroundPageStyle = prefsState.nonHomeBackgroundPageStyle,
        nonHomeBackgroundScrim = prefsState.nonHomeBackgroundScrim,
        nonHomeBackgroundDepthEnabled = prefsState.nonHomeBackgroundDepthEnabled,
        nonHomeBackgroundSaturation = prefsState.nonHomeBackgroundSaturation,
        visibleBottomPageNames = prefsState.visibleBottomPageNames,
        onVisibleBottomPageNamesChange = prefsState::updateVisibleBottomPageNames,
        privilegeStatus = privilegeStatus,
        privilegedShell = privilegedShell,
        mcpServerManager = mcpServerManager,
        onOpenGuideDetail = onOpenGuideDetail,
        onOpenBaActivityCalendar = onOpenBaActivityCalendar,
        onOpenBaPool = onOpenBaPool,
        requestedBottomPage = requestedBottomPage,
        requestedBottomPageToken = requestedBottomPageToken,
        requestedGitHubRefreshToken = requestedGitHubRefreshToken,
        requestedGitHubActionsTrackId = requestedGitHubActionsTrackId,
        requestedGitHubActionsSheetToken = requestedGitHubActionsSheetToken,
        requestedBaAccountId = requestedBaAccountId,
        requestedBaAccountToken = requestedBaAccountToken,
        onRequestedBottomPageConsumed = onRequestedBottomPageConsumed,
        onBaGuideCatalogOpen = onBaGuideCatalogOpen,
        onBaGuideCatalogBack = onBaGuideCatalogBack,
    )
